-- Generate all transfer commands in a single query
SELECT 
  CASE 
    WHEN OBJECT_TYPE IN ('DATABASE', 'SCHEMA') THEN
      'GRANT OWNERSHIP ON ' || OBJECT_TYPE || ' ' || OBJECT_NAME || ' TO ROLE role_b REVOKE CURRENT GRANTS;'
    ELSE
      'GRANT OWNERSHIP ON ' || OBJECT_TYPE || ' ' || OBJECT_NAME || 
      ' IN SCHEMA ' || OBJECT_SCHEMA || ' TO ROLE role_b REVOKE CURRENT GRANTS;'
  END AS TRANSFER_COMMAND
FROM SNOWFLAKE.ACCOUNT_USAGE.OBJECT_PRIVILEGES
WHERE PRIVILEGE = 'OWNERSHIP' 
  AND GRANTEE = 'ROLE_A'
  AND DELETED_ON IS NULL;
